spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest # 가장 최근의 메시지부터 읽기 시작
    #      properties:
    #        spring.json.trusted.packages: "*" # 신뢰할수있는 패키지 경로 (역직렬화시 모드패키지 신뢰가있어야지 가능)
    #        allow.auto.create.topic: false # 존재하지 않는 토픽에 대해 자동으로 토픽을 생성하는 것을 금지
    #    listener:
    #      concurrency: 1 # 리스너 컨테이너의 동시성을 설정 - 여기서는 1로 설정되어 있어, 하나의 스레드만 사용하여 메시지를 처리
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#  datasource:
#    url: jdbc:mysql://localhost:3306/campus?serverTimezone=Asia/Seoul
#    username: myuser
#    password: mypassword
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
